# Generated by Django 4.0.6 on 2022-08-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('subject', models.CharField(choices=[('General Info', 'General Info'), ('Suggest a Feature', 'Suggest a Feature'), ('Report a Problem', 'Report a Problem'), ('Privacy', 'Privacy')], max_length=50)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
    ]
