# Generated by Django 4.0.6 on 2022-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunker', '0003_delete_ouruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['-saved_on']},
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
    ]
